### ISSUE TITLE
Move to BEM convention

### ISSUE THREAD

**Issue by FezVrasta** [franciscop/flexpoint#2]
You could move this grid to BEM convention.

It would become easier to use and you could advertise as the only grid system based on BEM (that I'm aware of...)

**Comment by franciscop** [comment]
Sorry but I don't really like BEM and most people I know don't like it either (that might be the reason there's none yet?). Nothing stops you from forking and BEM-ing it though :wink:

**Comment by FezVrasta** [comment]
Yup I didn't liked it as well until I started working on huge projects :/
